### PR TITLE
Trying to fix Theater page logic

### PR DESCRIPTION
**Pull request by TulvanAndrei**
Please see the attached gif of how this works now.

Theater Tab - Fixing All Off Logic

### CODE REVIEW

**Comment by grgur** [comment]
Looks like it's working. One more thing: When `All Off` (Activities section) and I click on a Device, I would expect the TV Activity to be activated

image

**Comment by TulvanAndrei** [comment]
> Looks like it's working. One more thing: When `All Off` (Activities section) and I click on a Device, I would expect the TV Activity to be activated
> 
> image

Makes sense, I'll try to make that work.

**Comment by TulvanAndrei** [comment]
> Looks like it's working. One more thing: When `All Off` (Activities section) and I click on a Device, I would expect the TV Activity to be activated
> 
> image

Fixed in the latest commit, please see gif bellow:

Theater Tab - Fixing All Off Logic

**Comment by TulvanAndrei** [comment]
Removed master volume if "All Off" is selected. Please see below.

Removing volume controls

**Comment by grgur** [comment]
Thanks @TulvanAndrei

**Pull request merged**
